/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AdcDateRelative {
    'date': string;
    'locale': string;
  }
  interface AdcDateRelativeAttributes extends StencilHTMLAttributes {
    'date'?: string;
    'locale'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AdcDateRelative': Components.AdcDateRelative;
  }

  interface StencilIntrinsicElements {
    'adc-date-relative': Components.AdcDateRelativeAttributes;
  }


  interface HTMLAdcDateRelativeElement extends Components.AdcDateRelative, HTMLStencilElement {}
  var HTMLAdcDateRelativeElement: {
    prototype: HTMLAdcDateRelativeElement;
    new (): HTMLAdcDateRelativeElement;
  };

  interface HTMLElementTagNameMap {
    'adc-date-relative': HTMLAdcDateRelativeElement
  }

  interface ElementTagNameMap {
    'adc-date-relative': HTMLAdcDateRelativeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
