/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AdcDateRelative {
    /**
    * [Required] The date and time to compare with. The base date is always the equivalent to Date.now().
    */
    'datetime': string;
    /**
    * [Optional] A locale for formatting the relative date. If no locale is specified, or if it's not a valid locale, the component will fallback to the browser's locale.
    */
    'locale': string;
  }
  interface AdcDateRelativeAttributes extends StencilHTMLAttributes {
    /**
    * [Required] The date and time to compare with. The base date is always the equivalent to Date.now().
    */
    'datetime'?: string;
    /**
    * [Optional] A locale for formatting the relative date. If no locale is specified, or if it's not a valid locale, the component will fallback to the browser's locale.
    */
    'locale'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AdcDateRelative': Components.AdcDateRelative;
  }

  interface StencilIntrinsicElements {
    'adc-date-relative': Components.AdcDateRelativeAttributes;
  }


  interface HTMLAdcDateRelativeElement extends Components.AdcDateRelative, HTMLStencilElement {}
  var HTMLAdcDateRelativeElement: {
    prototype: HTMLAdcDateRelativeElement;
    new (): HTMLAdcDateRelativeElement;
  };

  interface HTMLElementTagNameMap {
    'adc-date-relative': HTMLAdcDateRelativeElement
  }

  interface ElementTagNameMap {
    'adc-date-relative': HTMLAdcDateRelativeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
