/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AdcDate {}
  interface AdcDateAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AdcDate': Components.AdcDate;
  }

  interface StencilIntrinsicElements {
    'adc-date': Components.AdcDateAttributes;
  }


  interface HTMLAdcDateElement extends Components.AdcDate, HTMLStencilElement {}
  var HTMLAdcDateElement: {
    prototype: HTMLAdcDateElement;
    new (): HTMLAdcDateElement;
  };

  interface HTMLElementTagNameMap {
    'adc-date': HTMLAdcDateElement
  }

  interface ElementTagNameMap {
    'adc-date': HTMLAdcDateElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
